### PR TITLE
Get sensor IPv4 via PhoXi API [BIPI-6338]

### PR DESCRIPTION
**Pull request by PatrikBakyta**
Check sensor drop-downs in Studio web interface or execute:
`rosservice call /phoxi_camera/get_device_list "{}"`

### CODE REVIEW

**Review by jcimerman — APPROVED** [review]

**Review by mikiPhotoneo — APPROVED** [review]
maybe developers should handle these tasks in the future O:-)

**Review by AdamSojkaPho — APPROVED** [review]
ok

**Comment by PatrikBakyta** [comment]
> maybe developers should handle these tasks in the future O:-)

I consider myself a part-time developer :)

**Comment by PatrikBakyta** [comment]
@ooruban please give it a look

**Pull request merged**
